"""
Build python classes from netlink header struct definitions

Two C programs are generated at stage 1 of the process.

At stage 2, C programs are compiled and executed. One produces the final
result - Python "defs.py" with values of defines and enums, and the other
produces Python "sizes.py" to be used at stage 3.

This is stage 3. It parses headers "properly" and generates Python file
with class definition for structures.
"""

from collections import deque
from enum import Enum
from io import TextIOWrapper
from os import getenv
from pycparser import CParser
from pycparser.c_ast import (
    ArrayDecl,
    Constant,
    Decl,
    IdentifierType,
    Node,
    NodeVisitor,
    PtrDecl,
    Struct,
    TypeDecl,
    Union,
)
from struct import calcsize
from struct import error as StructError
from subprocess import PIPE, Popen, run, STDOUT
from sys import argv, stderr
from tempfile import mkstemp
from typing import (
    Any,
    ContextManager,
    Deque,
    Dict,
    IO,
    List,
    NamedTuple,
    Set,
    Tuple,
    Type,
)
from typing import Dict as DictT
from typing import Literal as LiteralT
from typing import Optional as OptionalT
from types import TracebackType
from black import format_file_contents, Mode

from headers import INC, HEADERS, PREINC
from namelist import structs_unions

CLASSHDR = """\
\"\"\" Autogenerated file, do not edit! \"\"\"

# pylint: disable-all
from struct import pack
from typing import Any, Callable, ClassVar, Dict, List, TypeVar, Union

Accum = TypeVar("Accum")
class NllHdr(Dict[str, Any]):
    PACKFMT: ClassVar[str]
    SIZE: ClassVar[int]

    def __bytes__(self) -> bytes:
        return pack(
            self.PACKFMT,
            *(
                default if callable(kwarg) else kwarg
                for kwarg, default in zip(
                    self.values(),
                    self.__init__.__kwdefaults__.values(),  # type: ignore
                )
            ),
        )
"""

CPP = "/usr/bin/cpp"

FMTDICT: Dict[Tuple[str, ...], str] = {
    ("atomic_bool",): "B",  # Artefact of fake_includes
    ("unsigned", "short", "int"): "H",
    ("unsigned", "int"): "I",
    ("__u8",): "B",
    ("__be64",): "8s",
    ("__s8",): "b",
    ("__s64",): "q",
    ("__u32",): "L",
    ("unsigned", "short"): "H",
    ("int",): "i",
    ("__kernel_sa_family_t",): "H",
    ("__s32",): "l",
    ("__sum16",): "H",
    ("unsigned",): "I",
    ("short",): "h",
    ("__u64",): "Q",
    ("unsigned", "char"): "B",
    ("__be32",): "4s",
    ("__be16",): "2s",
    ("__u16",): "H",
    ("signed", "char"): "b",
    ("unsigned", "long"): "L",
    ("char",): "b",
}

size_cache: Dict[str, int] = {}


class Kind(Enum):
    Struct = 1
    Union = 2
    Pointer = 3
    Scalar = 4


class Element(NamedTuple):
    """Attribute of the generated NllHdr object"""

    name: str
    kind: Kind  # of the element of the array, if this is an array
    size: int  # of the element of the array, if this is an array
    fmt: str  # for Scalar, value from FMTDICT
    dim: OptionalT[int] = None  # None: "not an array", 0 - size undefined

    def aname(self) -> str:
        # Attributes that start with "__" are "class-private", have to avoid.
        # Attribute named "from" is not possible, mangle it to start with "_".
        if self.name.startswith("__"):
            return self.name[1:]
        if self.name in ("from", "bytes"):
            return "_" + self.name
        return self.name

    def fmtspec(self, _parentname: str) -> str:
        if self.kind is Kind.Struct or self.kind is Kind.Union:
            return str(self.size) + "s"
        if self.kind is Kind.Pointer:
            return "Q"
        if self.kind is Kind.Scalar:
            return self.fmt


class Item(NamedTuple):
    """Description of the NllHdr object to generate"""

    name: str
    kind: Kind  # only Struct or Union. Do we need Union?...
    size: int
    bitsize: OptionalT[int]
    elements: Tuple[Element, ...]

    def asclass(self) -> str:
        if self.name is None or self.size is None:
            return ""

        packfmt = "=" + "".join(el.fmtspec(self.name) for el in self.elements)
        try:
            size = calcsize(packfmt)
            size_cache[self.name] = size
        except StructError as e:
            print(e, packfmt, self.name, file=stderr)
            return ""

        if (self.kind.name.lower(), self.name) not in structs_unions:
            print("Don't need", self.name)
            return ""

        return ""

        classfile = f"\n\nclass {self.name}(NllHdr):\n"
        classfile += f'\t"""{self.kind.name} {self.name}"""\n'
        classfile += f'\tPACKFMT = "{packfmt}"\n'
        classfile += f"\tSIZE = {size}\n\n"
        init_args = ", ".join(
            "{name}: Union[Callable[[Accum, {t}], Accum], {t}] = {d}".format(
                name=el.aname(),
                **(
                    {"t": "bytes", "d": str(b"\0" * el.dim)}
                    if el.fmt == "s" and el.dim != ""
                    else (
                        {"t": "List[int]", "d": str([0] * el.dim)}
                        if el.dim
                        else {"t": "int", "d": "0"}
                    )
                ),
            )
            for el in self.elements
            if el.name is not None
        )
        super_args = ", ".join(
            f"{el.aname()}={el.aname()}"
            for el in self.elements
            if el.name is not None
        )
        classfile += f"\tdef __init__(self, *, {init_args}) -> None:\n"
        classfile += f"\t\tsuper().__init__({super_args})\n"
        return classfile


class UnionStructVisitor(NodeVisitor):
    """Custom node visitor object for pycparser"""

    def __init__(self, stage: Union[LiteralT[3],LiteralT[5]]) -> None:
        super().__init__()
        self.stage = stage
        self.stack: Deque = deque()
        self.need_dim: Set[Tuple[OptionalT[str], str, OptionalT[str]]] = set()
        self.need_size: Set[Tuple[OptionalT[str], str, OptionalT[str]]] = set()
        self.outstring: str = ""

    def _ancestry(self) -> Tuple[str, str, str]:
        # returns tuple (root_kind, root_name, string_of_qualifiers)
        # print("STACK", self.stack)
        q: List[str] = []
        for k, n in iter(self.stack):
            if k is not None and n is not None:
                break
            if n is not None:
                q.append(n)
        # For a typedef over unnamed struct, yield k=None, n=root_n
        # print(k, n, list(reversed(q)))
        return k, n, "".join(f"{el}." for el in reversed(q) if el != n)

    def visit_TypeDecl(self, node: Node) -> None:
        """For typedefs that give a name to unnamed structs/unions"""
        self.stack.appendleft((None, node.declname))
        super().generic_visit(node)
        self.stack.popleft()

    def _visit_struct_union(self, node: Node) -> None:
        self.stack.appendleft((node.__class__.__name__.lower(), node.name))
        ikind = Kind.Struct if isinstance(node, Struct) else Kind.Union

        isize = 0

        root_k, root_n, quals = self._ancestry()
        elems: List[Element] = []
        for decl in node.decls or []:  # decls is None if there's no body
            # Collect Elements for this Item
            if decl.name is None:  # Not interested in anonymous constructs
                continue

            fmt: Tuple[int, str] = (0, "")
            bitsize: OptionalT[int] = None
            if isinstance(decl.type, ArrayDecl):
                # print("Array", decl.type.dim)
                dim: OptionalT[int] = 0
                if decl.type.dim is not None:  # None is unspec len "[]"
                    # print("DIM", root_k, root_n, quals, decl.name)
                    self.need_dim.add((root_k, root_n, quals + decl.name))
                membertype = decl.type.type
            else:
                dim: OptionalT[int] = None
                membertype = decl.type

            if isinstance(membertype, TypeDecl):
                innertype = membertype.type
            elif isinstance(membertype, (Struct, Union, PtrDecl)):
                innertype = membertype
            else:
                raise RuntimeError(f"Unfamiliar {membertype} in {node.name}")

            if decl.bitsize is not None and not isinstance(
                innertype, IdentifierType
            ):
                raise RuntimeError(
                    f"bitsize is present for non-identifier: {decl}"
                )

            if isinstance(innertype, IdentifierType):
                ekind = Kind.Scalar
                esize = 0
                self.need_size.add(
                    (
                        None,
                        " ".join(
                            nm for nm in innertype.names if nm != "unsigned"
                        ),
                        None,
                    )
                )
                fmt = FMTDICT[tuple(sorted(innertype.names, reverse=True))]
                if decl.bitsize is not None:
                    if (
                        not isinstance(decl.bitsize, Constant)
                        or decl.bitsize.type != "int"
                    ):
                        raise RuntimeError(f"Unsupported bitsize in {decl}")
                    bitsize = decl.bitsize.value
            elif isinstance(innertype, (Struct, Union)):
                ekind = (
                    Kind.Struct
                    if isinstance(innertype, Struct)
                    else Kind.Union
                )
                esize = 0  # struc_union_sizes.get(innertype.name, None)
                if dim == 0:
                    print("Skip need_size for", root_k, root_n, quals + decl.name)
                else:
                    self.need_size.add((root_k, root_n, quals + decl.name))
            elif isinstance(innertype, PtrDecl):
                ekind = Kind.Pointer
                esize = 0  # struc_union_sizes.get("__pointer", None)
                self.need_size.add((None, "__pointer", None))
            else:
                raise RuntimeError(f"Unfamiliar {decl} in {node.name}")

            # print(f"(({root_k} {root_n} *)0)->{quals}{decl.name}", ekind, fmt)
            elems.append(Element(decl.name, ekind, esize, fmt, dim))

        # self.outstring += Item(
        #     node.name, ikind, isize, bitsize, tuple(elems)
        # ).asclass()
        super().generic_visit(node)
        self.stack.popleft()

    visit_Union = _visit_struct_union
    visit_Struct = _visit_struct_union


CCODE = (
    """\
#include <linux/sockios.h>  /* Needed for linux/if_tunnel.h */
#include <stdio.h>""",
    """\

struct vn {char *n; long long unsigned v;} sizelist[] = {""",
    """\
\t{NULL, 0},
};

struct vn {char *n; long long unsigned v;} dimlist[] = {""",
    """\
\t{NULL, 0},
};

int main(int const argc, char const * const argv[])
{
\tstruct vn *cur;

\tprintf("\\"\\"\\" Autogenerated file, do not edit! \\"\\"\\"\\n\\n");
\tprintf("# pylint: disable-all\\n\\n");
\tprintf("csizes = {\\n");
\tfor (cur = sizelist; cur->n != NULL; cur++) {
\t\tprintf("    \\"%s\\": %llu,\\n", cur->n, cur->v);
\t}
\tprintf("}\\n\\n");
\tprintf("cdims = {\\n");
\tfor (cur = dimlist; cur->n != NULL; cur++) {
\t\tprintf("    \\"%s\\": %llu,\\n", cur->n, cur->v);
\t}
\tprintf("}\\n");
\treturn 0;
}""",
)


if __name__ == "__main__":
    if "-3" in argv:
        stage = 3
    elif "-5" in argv:
        stage = 5
    else:
        raise RuntimeError("Must specify \"-3\" or \"-5\" argument")

    extra_headers = tuple(
        []
        if (envval := getenv("NLL_EXTRA_HEADERS")) is None
        else envval.split(",")
    )

    with Popen(
        [CPP, "-Ifake_libc_include"],
        stdin=PIPE,
        stdout=PIPE,
        stderr=PIPE,
        encoding="ascii",
    ) as proc:
        assert isinstance(proc.stdout, TextIOWrapper) and isinstance(
            proc.stderr, TextIOWrapper
        )
        proc.stdin.write(
            PREINC
            + "\n".join(
                f"#include <{hdr}>" for hdr in (HEADERS + extra_headers)
            )
        )
        proc.stdin.close()
        ast = CParser().parse(proc.stdout.read(), "combined_headers.c")
    structs = UnionStructVisitor(stage)
    structs.visit(ast)

    # print("SIZE CACHE", size_cache)
    if stage == 3:
        # print("NEED SIZE", structs.need_size)
        # print("NEED DIM ", structs.need_dim)
        with open("mksize.c", "w") as out:
            print(CCODE[0], file=out)
            for hdr in HEADERS + extra_headers:
                print(f"#include <{hdr}>", file=out)
            print(CCODE[1], file=out)
            for k, n, e in structs.need_size:
                if not n:
                    print("NO NAME!", (k, n, e))
                    continue
                if n == "atomic_bool":
                    continue
                if n == "__pointer":
                    print(f'\t{{ "{n}", sizeof(void *) }},', file=out)
                elif k is None:
                    print(f'\t{{ "{n}", sizeof({n}) }},', file=out)
                elif e is None:
                    print(f'\t{{ "{n}", sizeof({k} {n}) }},', file=out)
                else:
                    print(
                        f'\t{{ "{n}.{e}", sizeof((({k} {n}*)0)->{e}) }},', file=out
                    )
            print(CCODE[2], file=out)
            for k, n, e in structs.need_dim:
                print(
                    f'\t{{ "{n}.{e}", sizeof((({'' if k is None else k} {n}*)0)->{e}) / sizeof((({'' if k is None else k} {n}*)0)->{e}[0]) }},', file=out
                )
                # if n in size_cache:
                #     print(k, n, e, size_cache[n])
                # else:
                #     print(k, n, e, "UNKNOWN")
            print(CCODE[3], file=out)
    else:  # stage == 5
        if False:
            print(
                format_file_contents(
                    structs.outstring, fast=False, mode=Mode(line_length=79)
                ),
                end="",
            )
        else:
            print(structs.outstring)
