"""
Generate temporary C programs that genrarate Python code for defs and sizes
of various objects in the kernel headers used for netlink operations.

Include build dependency on `linux-libc-dev` package

Generating two C programs is stage 1 of the process.

On stage 2, C programs are compiled and executed. One produces the final
result - Python "defs.py" with values of defines and enums, and the other
produces Python "sizes.py" to be used at stage 3.

Stage 3 parses headers "properly" and generates Python file with class
definition for structures.
"""

from collections import OrderedDict
from contextlib import ExitStack
from io import TextIOWrapper
from os import getenv, unlink
from os.path import join
from subprocess import PIPE, Popen, run, STDOUT
from sys import argv
from tempfile import mkstemp
from typing import Any, ContextManager, IO, List, Literal, Set, Tuple, Type
from typing import Dict as DictT
from typing import Literal as LiteralT
from typing import Optional as OptionalT
from types import TracebackType
from black import format_file_contents, Mode
from pyparsing import *
from pyparsing import pyparsing_common as pc

from headers import INC, HEADERS, PREINC, EXCL_DEFS

CPP = "/usr/bin/cpp"

CCDEFS = (
    """\
#include <stdio.h>
#include <asm-generic/ioctls.h>
#include <linux/sockios.h>""",
    """\

struct vn {char *n; long long unsigned v; char *s;} list[] = {""",
    """\
\t{NULL, 0, NULL},
};

int main(int const argc, char const * const argv[])
{
\tstruct vn *cur;

\tprintf("\\"\\"\\"Autogenerated file, do not edit!\\"\\"\\"\\n\\n");
\tprintf("# pylint: disable-all\\n\\n");
\tfor (cur = list; cur->n != NULL; cur++) {
\t\tif (cur->s)
\t\t\tprintf("%s = \\"%s\\"\\n", cur->n, cur->s);
\t\telse
\t\t\tprintf("%s = %llu\\n", cur->n, cur->v);
\t}
\treturn 0;
}""",
)


class mkstemp_n:
    def __init__(self, count: int = 2) -> None:
        self.temps = tuple(mkstemp() for _ in range(count))

    def __enter__(self) -> Tuple[IO, ...]:
        files: List[IO] = []
        with ExitStack() as stk:
            for fd, _ in self.temps:
                files.append(
                    stk.enter_context(open(fd, "r+", encoding="utf-8"))
                )
                self.undo = stk.pop_all()
        return tuple(files)

    def __exit__(
        self,
        ecls: OptionalT[Type[BaseException]],
        eobj: OptionalT[BaseException],
        etrc: OptionalT[TracebackType],
    ) -> LiteralT[False]:
        with self.undo:
            pass
        for _, fn in self.temps:
            try:
                unlink(fn)
            except OSError:
                pass
        return False


c_style_comment = Combine(Regex(r"/\*(?:[^*]|\*(?!/))*") + "*/")
CHAR, SHORT, INT, LONG = (Literal(x) for x in ("char", "short", "int", "long"))
stdtype = CHAR ^ SHORT ^ INT ^ LONG
nonstdtype = Or(
    Literal(x)
    for x in (
        "__" + pfx + str(sz)
        for pfx in ("s", "u", "be")
        for sz in (8, 16, 32, 64)
    )
)
# syntax we don't want to see in the final parse tree
LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET, EQ, COMMA, SEMICOLON = (
    Suppress(x) for x in "(){}[]=,;"
)

arith_op = Word("+-*/", max=1)
arith_elem = pc.identifier ^ pc.integer
arith_expr = Group(arith_elem + (arith_op + arith_elem)[...])
paren_expr = arith_expr ^ (LPAREN + arith_expr + RPAREN)

# Enums
enum_elem = Group(pc.identifier("name") + Optional(EQ + paren_expr("value")))
enum_body = (
    Suppress(LBRACE)
    + Group(enum_elem + (COMMA + enum_elem)[...] + Optional(COMMA))("group")
    + Suppress(RBRACE)
)
enum = Suppress("enum") + Optional(pc.identifier("ename")) + enum_body
enum.ignore(c_style_comment)

# Structs and unions body has to be a recusive definition
stun_body = Forward()

typespec = Combine(
    Group(Optional(Literal("unsigned") ^ Literal("signed")) + stdtype)
    ^ nonstdtype
    ^ Group(Literal("struct") + pc.identifier + Optional(stun_body))
    ^ Group(Literal("union") + pc.identifier + Optional(stun_body)),
    adjacent=False,
)

typedvar = Group(
    typespec("typespec")
    + pc.identifier("name")
    + Optional(
        Group(LBRACKET + Optional(arith_expr)("val") + RBRACKET)("dim")
        ^ Group(Literal(":") + pc.integer)
    )
    + SEMICOLON
)

stun_body << (
    Suppress(LBRACE) + Group(typedvar[...])("elist") + Suppress(RBRACE)
)

struct = (
    Literal("struct")("kind") + pc.identifier("name") + Optional(stun_body)
)
struct.ignore(c_style_comment)

union = Literal("union")("kind") + pc.identifier("name") + Optional(stun_body)
union.ignore(c_style_comment)

typedef = (
    Literal("typedef")("kind")
    + Optional(pc.identifier)
    + stun_body
    + pc.identifier("name")
)

struct_or_union_or_typedef = struct ^ union ^ typedef

# Defines
define = (
    LineStart()
    + Suppress("#define")
    + pc.identifier("name")
    + White(" \t")
    + Char(printables)("valstart")  # Unreliable indicator if it's a string
)
define.ignore(c_style_comment)

if __name__ == "__main__":
    extra_headers = tuple(
        []
        if (envval := getenv("NLL_EXTRA_HEADERS")) is None
        else envval.split(",")
    )

    ### Parse headers one by one, without preprocessing. Find defines and enums.

    names = {}  # dict with key=name, val=is-it-a-string?
    for infn in HEADERS + extra_headers:
        with mkstemp_n() as (defs, rest), open(join(INC, infn)) as inp:
            line = ""
            for rline in inp.readlines():
                line += rline
                if line.endswith("\\\n"):
                    line = line.rstrip("\\\n")
                    continue
                if line.startswith("#define"):
                    defs.write(line)
                else:
                    rest.write(line)
                line = ""
            defs.seek(0)
            rest.seek(0)
            # find instances of defines ignoring other syntax
            for item, start, stop in define.scanString(defs.read()):
                if item.name:
                    names[item.name] = item.valstart == '"'
                else:
                    print("****************\n", item.dump())
            # find instances of enums ignoring other syntax
            for item, start, stop in enum.scanString(rest.read()):
                for elem in item.group:
                    if not elem.name.startswith("__"):
                        names[elem.name] = False

    with open("mkdefs.c", "w") as out:
        print(CCDEFS[0], file=out)
        for hdr in HEADERS + extra_headers:
            print(f"#include <{hdr}>", file=out)
        print(CCDEFS[1], file=out)
        for name, isastring in names.items():
            if name in EXCL_DEFS:
                continue
            if isastring:
                print(f'\t{{ "{name}", 0ll, {name} }},', file=out)
            else:
                print(f'\t{{ "{name}", {name}, NULL }},', file=out)
        print(CCDEFS[2], file=out)

    ### Parse headers one by one, after preprocessing. Find structs and unions.

    # Potential aliases for structs_and_unions, include them first
    # structs_and_unions = {excl: None for excl in EXCL_DEFS}
    structs_and_unions = {}
    arrays = set()
    for infn in HEADERS + extra_headers:
        # process = run(
        #     [CPP, join(INC, infn)],
        #     stdout=PIPE,
        #     stderr=STDOUT,
        #     encoding="ascii",
        #     check=True,
        # )
        # ccode = "\n".join(
        #     filter(lambda s: not s.startswith("#"), process.stdout.split("\n"))
        # )
        with open(join(INC, infn)) as inp:
            ccode = inp.read()
            for item, start, stop in struct_or_union_or_typedef.scanString(
                ccode
            ):
                structs_and_unions[item.name] = item.kind

    with open("namelist.py", "w") as out:
        print('"""Generated list of interesting names"""\n', file=out)
        print("structs_unions = set((", file=out)
        for name, kind in structs_and_unions.items():
            print(f'    ("{kind}", "{name}"),', file=out)
        print("))", file=out)
